[project]
name = "res-setting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dearpygui>=2.2",
    "pyserial>=3.5",
]
